---
title: "Tesla_Presentation"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r}
# Libraries 
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(scales)

Electric_Vehicle_Population_Data = read_csv("Electric_Vehicle_Population_Data.csv")

df = Electric_Vehicle_Population_Data

#Data Cleaning 

clean_df <- df %>%
  rename_all(~ gsub('[ .]', '_', .)) %>%
  mutate(
    Base_MSRP = as.numeric(Base_MSRP),
    Tesla = ifelse(Make == 'TESLA', 'TESLA', 'OTHERS')
  )

#1. What percentage of EVs in Washington are Tesla? 
# Tesla/all vehicles * 100 

total_vehicle = nrow(clean_df)
tesla_vehicle = clean_df %>% filter(Tesla == 'TESLA') %>% nrow()
tesla_market_share = round(tesla_vehicle/total_vehicle * 100, 1)

#2. Top Tesla Models Selling in the Area
# How much are we making from these models? 

make_model_sold = clean_df %>%
  filter(Tesla == 'TESLA') %>%
  group_by(Make,Model) %>%
  summarise(count_sold = n(), .groups = 'drop') %>%
  arrange(desc(count_sold))
  
msrp_by_year = clean_df %>%
  filter(Base_MSRP > 0) %>%
  filter(Tesla == "TESLA") %>%
  group_by(Model_Year, Make, Model) %>%
  summarise(min(Base_MSRP))%>% 
  arrange(Model_Year, Make, Model)

df_tesla_prices <- read_csv("Tesla_Prices.csv")

#Transform data to upper 
df_tesla_prices = df_tesla_prices %>%
  mutate(
    Model = toupper(Model))
  
#Getting out numbers 
Top_Tesla_Models_Priced = make_model_sold %>%
  left_join(df_tesla_prices, by = 'Model')%>%
  mutate(
    Estimated_revenue = count_sold * Base_Price_USD)

#Final Estimates for lifetime sales 
Top_Tesla_Models_Priced = Top_Tesla_Models_Priced %>% 
  filter(!is.na(Estimated_revenue))%>%
  group_by(Model)%>%
  slice_min(Base_Price_USD) %>%
  ungroup()

#ADD IN
  tesla_sold_by_year = clean_df %>%
    filter(Tesla == "TESLA") %>%
    group_by(Model_Year)%>%
    summarise(Count = n()) %>%
    arrange(Model_Year)


#3. Tesla vs Competitors - Range MSRP

#AVG Range 
AVG_Range_For_Evs = clean_df %>%
  filter(Electric_Vehicle_Type == "Battery Electric Vehicle (BEV)",
         Electric_Range != 0, 
         Base_MSRP != 0) %>%
  group_by(Tesla) %>%
summarise(AVG_Range = mean(Electric_Range),
          AVG_MSRP = mean(Base_MSRP))

#Median Range 
Median_Range_For_Evs = clean_df %>%
  filter(Electric_Vehicle_Type == "Battery Electric Vehicle (BEV)",
         Electric_Range != 0,
         Base_MSRP != 0) %>%
  group_by(Tesla) %>%
  summarise(Median_Range = median(Electric_Range),
            Median_MSRP = median(Base_MSRP))


#4. PHEV vs BEV Trends 
phev_vs_bev = clean_df %>%
  group_by(Model_Year, Electric_Vehicle_Type) %>%
  summarise(Count = n(), .groups = 'drop')


#5. Top Electric Utilities in Washington for Tesla
Ultility_Count_for_Teslas = clean_df %>%
  filter(Tesla == 'TESLA') %>%
  group_by(Electric_Utility) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  arrange(desc(Count))%>%
  head(5)
```

### Tesla MArket Share in Wahsington (%)
```{r}
market_df = data.frame(
  Group = c('TESLA', 'OTHER'),
  Market_Share = c(tesla_market_share, 100 - tesla_market_share)
)

market_df = market_df %>%
  mutate(
    Label = paste0(Market_Share, '%'),
    ypos = cumsum(Market_Share) - 0.5 * Market_Share
  )


ggplot(market_df, aes(x = '', y = Market_Share, fill = Group)) + 
  geom_col(width = 1) + 
  coord_polar('y') + 
  geom_text(aes(y = ypos, label = Label)) +
  labs(title = 'Tesla Market Share in Washington (%)') +
  theme_void()
```

### Tesla Model Sold - All Time
```{r}

ggplot(make_model_sold, aes(x = reorder(Model, count_sold), y = count_sold )) +
  geom_col(fill = 'lightblue') +
  coord_flip() +
  labs(title = 'Tesla Model Sold - All Time') +
  theme_minimal()

```

### Estimated Revenue Per Model
```{r}
ggplot(Top_Tesla_Models_Priced, aes(x = reorder(Model, Estimated_revenue), y = Estimated_revenue )) +
  geom_col(fill = 'forestgreen') +
  coord_flip() +
  labs(title = 'Estimated Revenue Per Model') +
  scale_y_continuous(labels = label_comma()) +
  theme_minimal()
```

### Tesla Vehicles Sold by Year
```{r}
ggplot(tesla_sold_by_year, aes(x = Model_Year, y = Count)) +
    geom_line(color = 'lightblue', size = 1.5) +
    geom_point(color = 'red', size = 2) +
    labs(title = 'Tesla Vehicles Sold by Year') +
    theme_minimal()
```

### AVG Electric Range (BEV)
```{r}
ggplot(AVG_Range_For_Evs, aes( x = Tesla, y = AVG_Range, fill = Tesla))+
  geom_col() +
  labs(title = "AVG Electric Range (BEV)") +
  theme_minimal()
```

### AVG MSRP (BEV)
```{r}
ggplot(AVG_Range_For_Evs, aes( x = Tesla, y = AVG_MSRP, fill = Tesla))+
  geom_col() +
  labs(title = "AVG MSRP (BEV)") +
  theme_minimal()
```

### PHEV vs BEV Trends Over Time
```{r}
ggplot(phev_vs_bev, aes(x = Model_Year, y = Count, color = Electric_Vehicle_Type)) +
  geom_line(size = 1.5) +
  geom_point(size = 2) +
  scale_x_continuous(breaks = seq(2000, 2025, 5), limits = c(2008, 2025)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  labs(title = 'PHEV vs BEV Trends Over Time') +
  theme_minimal(base_size = 14) +
  theme(aspect.ratio = 0.5,
        legend.position = "bottom",
        legend.title = element_blank())
```

### Top Electric Utilities in Washington
```{r}
ggplot(Ultility_Count_for_Teslas, aes(x = reorder(Electric_Utility, Count), y = Count)) +
  geom_col( fill = 'steelblue') + 
  coord_flip() + 
  labs(title = 'Top Electric Utilities in Washington', x = 'Utility', y = 'Tesla Count') + 
  theme_minimal() +
  theme(axis.text.y = element_text(size = 5))
```